export const dashboard = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Clonedivers performance</title>
<style>body{background:#101722;color:#e6ecf5;font:16px system-ui;margin:32px;max-width:1400px}input,button{font:inherit;padding:9px;margin:4px;background:#203047;color:inherit;border:1px solid #566781;border-radius:5px}table{border-collapse:collapse;width:100%;margin-top:20px}td,th{text-align:left;border-bottom:1px solid #354459;padding:10px}pre{white-space:pre-wrap;overflow-wrap:anywhere}small{color:#a9b7ca}canvas{width:100%;height:220px;background:#152033}</style>
<h1>Clonedivers performance</h1><p>Session timelines from the squad. Foreground includes menus and loading screens; compare similar gameplay.</p>
<form id="login"><input id="key" type="password" placeholder="Owner access key" autocomplete="off"><button>Open dashboard</button></form><button id="logout" hidden>Lock</button><p id="status"></p><div id="sessions"></div><h2 id="heading"></h2><canvas id="chart" width="1200" height="220" hidden></canvas><pre id="details"></pre>
<script>
let token=''; const el=id=>document.getElementById(id); const say=t=>el('status').textContent=t;
async function api(path){const r=await fetch(path,{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error('Request failed ('+r.status+')');return r.json()}
el('logout').onclick=()=>location.reload();
el('login').onsubmit=async e=>{e.preventDefault();token=el('key').value;el('key').value='';try{const rows=await api('/admin/sessions');el('login').hidden=true;el('logout').hidden=false;showSessions(rows);say(rows.length+' recent sessions')}catch(e){say(e.message);token=''}};
function showSessions(rows){const t=document.createElement('table');const h=t.insertRow();for(const s of ['Player','Started','Last record','Records','MiB',''])h.insertCell().textContent=s;for(const r of rows){const tr=t.insertRow();for(const v of [r.nickname,new Date(r.start).toLocaleString(),new Date(r.end).toLocaleString(),r.records,(r.bytes/1048576).toFixed(1)])tr.insertCell().textContent=v;const b=document.createElement('button');b.textContent='Inspect';b.onclick=()=>inspect(r);tr.insertCell().append(b)}el('sessions').replaceChildren(t)}
async function inspect(s){try{say('Loading session…');el('heading').textContent=s.nickname+' · '+new Date(s.start).toLocaleString();const chunks=await api('/admin/session/'+s.session_id);let rows=[];for(const c of chunks){rows.push(...(await api('/admin/chunk/'+c.id)).records);if(rows.length>250000){say('Showing first 250,000 records; download individual chunks for more.');break}}rows.sort((a,b)=>Date.parse(a.utc)-Date.parse(b.utc));const context=rows.filter(r=>r.kind==='context');const events=rows.filter(r=>r.kind==='event'||r.kind==='crash');const resources=rows.filter(r=>r.kind==='resource');const groups=new Map();for(const r of rows.filter(r=>r.kind==='frame')){const k=r.fields.SwapChainAddress||'unknown';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}const frames=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[];const intervalField=['CPUFrameTime','MsBetweenPresents','MsBetweenAppStart'].find(k=>frames.some(r=>typeof r.fields[k]==='number'));const vals=frames.map(r=>r.fields[intervalField]).filter(v=>typeof v==='number'&&v>0).sort((a,b)=>a-b);const stats=vals.length?{frames:vals.length,intervalField,fps:1000/(vals.reduce((a,b)=>a+b,0)/vals.length),p95Ms:vals[Math.ceil(vals.length*.95)-1],p99Ms:vals[Math.ceil(vals.length*.99)-1],over50Ms:vals.filter(v=>v>50).length,method:'Largest swapchain; includes foreground/background, menus and loading; not display FPS'}:{frames:0};el('details').textContent=JSON.stringify({context,frameStatistics:stats,resourceSamples:resources.length,events},null,2);draw(resources);say('Loaded '+rows.length+' records. Resource chart: game private memory (GiB).')}catch(e){say(e.message)}}
function draw(rows){const canvas=el('chart');canvas.hidden=!rows.length;const c=canvas.getContext('2d');c.clearRect(0,0,1200,220);const valid=rows.filter(r=>typeof r.fields.privateBytes==='number');if(!valid.length)return;const start=Date.parse(valid[0].utc),span=Math.max(1,Date.parse(valid.at(-1).utc)-start),max=Math.max(...valid.map(r=>r.fields.privateBytes),1);c.strokeStyle='#69baff';c.beginPath();valid.forEach((r,i)=>{const x=10+(Date.parse(r.utc)-start)/span*1180,y=200-r.fields.privateBytes/max*170;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.fillStyle='#dce8ff';c.fillText((max/1073741824).toFixed(2)+' GiB peak',12,15)}
</script></html>`;
