<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><StartupObject>ProfileReleaseCheck</StartupObject></PropertyGroup>
  <ItemGroup><Compile Include="../../Clonedivers/*.cs" Link="%(Filename)%(Extension)" /></ItemGroup>
</Project>
