<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><Reference Include="Clonedivers.Tests"><HintPath>../../Clonedivers.Tests/bin/Debug/net8.0-windows/Clonedivers.Tests.dll</HintPath></Reference></ItemGroup>
</Project>
